package co.edu.uptc.exceptions;

public enum TypingErrors {
    //Errores de gestion de personas 
    NAME_MIN_LENGTH, LASTNAME_MIN_LENGTH, NAME_EMPTY,LAST_NAME_EMPTY,INVALID_BIRTH_DATE,BIRTHDATE_BLANK,INVALID_EMAIL,EMAIL_MAX_LENGHT,EMAIL_EMPTY,INVALID_IDENTITY_CARD,INVALID_ID_CARD,INVALID_PASSPORT,INVALID_FOREIGN_ID,INVALID_OTHER_DOCUMENT,GENDER_BLANK,DUPLICATE_EMAIL, DUPLICATE_DOCUMENT, PERSON_NOT_FOUND, 

    //Errores de gestion de productos 
    CODE_ALPHANUMERIC_REQUIRED, CODE_INVALID_LENGTH,CODE_BLANK,CODE_NAME_MIN_LENGTH,CODE_NAME_MAX_LENGTH,CODE_NAME_BLANK,DESCRIPTION_MAX_LENGTH,CATEGORY_MIN_LENGTH,CATEGORY_BLANK,PRICE_MUST_BE_GREATER_THAN_ZERO,PRICE_INVALID_DECIMALS, QUANTITY_MUST_BE_POSITIVE,PRODUCT_NOT_FOUND, DUPLICATE_CODE; 
}
